title: "Berkeley O — Lead Cloud & DevOps Engineer"
description: "Production-grade architectures, runbooks, and automation across Azure, GCP, and Microsoft 365."
url: "https://berkeleyo.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
author:
  name: "Berkeley O"
  avatar: /assets/images/avatar.png
  bio: "Lead Cloud & DevOps Engineer — secure, scalable platforms on Azure, GCP, and Microsoft 365."
  location: "UK & Remote"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/berkeleyo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/<your-handle>"
logo: /assets/images/site-logo.png
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
